name: escola

services:
  # Serviço do banco de dados
  db:
    image: postgres:16-alpine
    container_name: escola-postgres
    # As variáveis do banco agora também vêm do .env
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - escola-network
    # ADICIONADO: Healthcheck para o banco de dados
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Gatway da aplicacao
  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gateway
    depends_on:
      db:
        condition: service_started
    ports:
      - "${CLIENT_SERVICE_PORT}:${CLIENT_SERVICE_PORT}"
      - "${CLIENT_SERVICE_DEBUG_PORT}:${CLIENT_SERVICE_DEBUG_PORT}"
    volumes:
      - .:/app
    env_file:
      - ./.env
    networks:
      - escola-network

networks:
  escola-network:
    driver: bridge

volumes:
  postgres-data: